# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputDialog(object):
    def setupUi(self, InputDialog):
        InputDialog.setObjectName("InputDialog")
        InputDialog.resize(700, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InputDialog.sizePolicy().hasHeightForWidth())
        InputDialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        InputDialog.setFont(font)
        self.BrowseButton = QtWidgets.QPushButton(InputDialog)
        self.BrowseButton.setGeometry(QtCore.QRect(10, 470, 121, 41))
        self.BrowseButton.setObjectName("BrowseButton")
        self.GeneticAlgorithmGroup = QtWidgets.QGroupBox(InputDialog)
        self.GeneticAlgorithmGroup.setGeometry(QtCore.QRect(380, 10, 311, 151))
        self.GeneticAlgorithmGroup.setObjectName("GeneticAlgorithmGroup")
        self.PopulationSpinner = QtWidgets.QSpinBox(self.GeneticAlgorithmGroup)
        self.PopulationSpinner.setGeometry(QtCore.QRect(160, 20, 141, 22))
        self.PopulationSpinner.setObjectName("PopulationSpinner")
        self.PopulationLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.PopulationLabel.setGeometry(QtCore.QRect(16, 20, 111, 20))
        self.PopulationLabel.setObjectName("PopulationLabel")
        self.IterationSpinner = QtWidgets.QSpinBox(self.GeneticAlgorithmGroup)
        self.IterationSpinner.setGeometry(QtCore.QRect(160, 50, 141, 22))
        self.IterationSpinner.setObjectName("IterationSpinner")
        self.IterationLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.IterationLabel.setGeometry(QtCore.QRect(16, 50, 111, 20))
        self.IterationLabel.setObjectName("IterationLabel")
        self.MutationSpinner = QtWidgets.QSpinBox(self.GeneticAlgorithmGroup)
        self.MutationSpinner.setGeometry(QtCore.QRect(160, 80, 141, 22))
        self.MutationSpinner.setObjectName("MutationSpinner")
        self.MutationLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.MutationLabel.setGeometry(QtCore.QRect(16, 80, 111, 20))
        self.MutationLabel.setObjectName("MutationLabel")
        self.SpawnSpinner = QtWidgets.QSpinBox(self.GeneticAlgorithmGroup)
        self.SpawnSpinner.setGeometry(QtCore.QRect(160, 110, 141, 22))
        self.SpawnSpinner.setObjectName("SpawnSpinner")
        self.SpawnLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.SpawnLabel.setGeometry(QtCore.QRect(16, 110, 111, 20))
        self.SpawnLabel.setObjectName("SpawnLabel")
        self.NestingGroup = QtWidgets.QGroupBox(InputDialog)
        self.NestingGroup.setGeometry(QtCore.QRect(380, 170, 311, 291))
        self.NestingGroup.setObjectName("NestingGroup")
        self.MagetLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MagetLabel.setGeometry(QtCore.QRect(10, 20, 111, 20))
        self.MagetLabel.setObjectName("MagetLabel")
        self.MagnetCombo = QtWidgets.QComboBox(self.NestingGroup)
        self.MagnetCombo.setGeometry(QtCore.QRect(160, 20, 141, 22))
        self.MagnetCombo.setObjectName("MagnetCombo")
        self.OpenLoopAngle = QtWidgets.QLabel(self.NestingGroup)
        self.OpenLoopAngle.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.OpenLoopAngle.setObjectName("OpenLoopAngle")
        self.OpenLoopCombo = QtWidgets.QComboBox(self.NestingGroup)
        self.OpenLoopCombo.setGeometry(QtCore.QRect(160, 50, 141, 22))
        self.OpenLoopCombo.setObjectName("OpenLoopCombo")
        self.InnerShapeLabel = QtWidgets.QLabel(self.NestingGroup)
        self.InnerShapeLabel.setGeometry(QtCore.QRect(10, 80, 111, 20))
        self.InnerShapeLabel.setObjectName("InnerShapeLabel")
        self.InnerShapeCombo = QtWidgets.QComboBox(self.NestingGroup)
        self.InnerShapeCombo.setGeometry(QtCore.QRect(160, 80, 141, 22))
        self.InnerShapeCombo.setObjectName("InnerShapeCombo")
        self.LinearStepLabel = QtWidgets.QLabel(self.NestingGroup)
        self.LinearStepLabel.setGeometry(QtCore.QRect(10, 110, 121, 20))
        self.LinearStepLabel.setObjectName("LinearStepLabel")
        self.AngularStepLabel = QtWidgets.QLabel(self.NestingGroup)
        self.AngularStepLabel.setGeometry(QtCore.QRect(10, 140, 121, 20))
        self.AngularStepLabel.setObjectName("AngularStepLabel")
        self.MaxWidthLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MaxWidthLabel.setGeometry(QtCore.QRect(10, 170, 121, 20))
        self.MaxWidthLabel.setObjectName("MaxWidthLabel")
        self.MaxHeightLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MaxHeightLabel.setGeometry(QtCore.QRect(10, 200, 121, 20))
        self.MaxHeightLabel.setObjectName("MaxHeightLabel")
        self.KerfLabel = QtWidgets.QLabel(self.NestingGroup)
        self.KerfLabel.setGeometry(QtCore.QRect(10, 230, 111, 20))
        self.KerfLabel.setObjectName("KerfLabel")
        self.MaxHeightSpinner = QtWidgets.QSpinBox(self.NestingGroup)
        self.MaxHeightSpinner.setGeometry(QtCore.QRect(160, 200, 141, 22))
        self.MaxHeightSpinner.setObjectName("MaxHeightSpinner")
        self.KerfSpinner = QtWidgets.QSpinBox(self.NestingGroup)
        self.KerfSpinner.setGeometry(QtCore.QRect(160, 230, 141, 22))
        self.KerfSpinner.setObjectName("KerfSpinner")
        self.AngularStepSpinner = QtWidgets.QSpinBox(self.NestingGroup)
        self.AngularStepSpinner.setGeometry(QtCore.QRect(160, 140, 141, 22))
        self.AngularStepSpinner.setObjectName("AngularStepSpinner")
        self.MaxWidthSpinner = QtWidgets.QSpinBox(self.NestingGroup)
        self.MaxWidthSpinner.setGeometry(QtCore.QRect(160, 170, 141, 22))
        self.MaxWidthSpinner.setObjectName("MaxWidthSpinner")
        self.LinearStepCombo = QtWidgets.QSpinBox(self.NestingGroup)
        self.LinearStepCombo.setGeometry(QtCore.QRect(160, 110, 141, 22))
        self.LinearStepCombo.setObjectName("LinearStepCombo")
        self.KerfSpinner_2 = QtWidgets.QSpinBox(self.NestingGroup)
        self.KerfSpinner_2.setGeometry(QtCore.QRect(160, 260, 141, 22))
        self.KerfSpinner_2.setObjectName("KerfSpinner_2")
        self.KerfLabel_2 = QtWidgets.QLabel(self.NestingGroup)
        self.KerfLabel_2.setGeometry(QtCore.QRect(10, 260, 141, 20))
        self.KerfLabel_2.setObjectName("KerfLabel_2")
        self.GeometryGroup = QtWidgets.QGroupBox(InputDialog)
        self.GeometryGroup.setGeometry(QtCore.QRect(10, 10, 361, 451))
        self.GeometryGroup.setObjectName("GeometryGroup")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.GeometryGroup)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 341, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.GeometryListLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.GeometryListLayout.setContentsMargins(0, 0, 0, 0)
        self.GeometryListLayout.setSpacing(0)
        self.GeometryListLayout.setObjectName("GeometryListLayout")
        self.CloseButton = QtWidgets.QPushButton(InputDialog)
        self.CloseButton.setGeometry(QtCore.QRect(570, 470, 121, 41))
        self.CloseButton.setObjectName("CloseButton")
        self.RunButton = QtWidgets.QPushButton(InputDialog)
        self.RunButton.setGeometry(QtCore.QRect(440, 470, 121, 41))
        self.RunButton.setObjectName("RunButton")

        self.retranslateUi(InputDialog)
        QtCore.QMetaObject.connectSlotsByName(InputDialog)

    def retranslateUi(self, InputDialog):
        _translate = QtCore.QCoreApplication.translate
        InputDialog.setWindowTitle(_translate("InputDialog", "Nesting"))
        self.BrowseButton.setText(_translate("InputDialog", "&Browse"))
        self.GeneticAlgorithmGroup.setTitle(_translate("InputDialog", "Genetic Algorithm"))
        self.PopulationLabel.setText(_translate("InputDialog", "Population"))
        self.IterationLabel.setText(_translate("InputDialog", "Iterations"))
        self.MutationLabel.setText(_translate("InputDialog", "Mutation Rate"))
        self.SpawnLabel.setText(_translate("InputDialog", "Spawn Rate"))
        self.NestingGroup.setTitle(_translate("InputDialog", "Nesting Process"))
        self.MagetLabel.setText(_translate("InputDialog", "Magnet"))
        self.OpenLoopAngle.setText(_translate("InputDialog", "Open Loop Action"))
        self.InnerShapeLabel.setText(_translate("InputDialog", "Allow Inner Shapes"))
        self.LinearStepLabel.setText(_translate("InputDialog", "Linear Step Size"))
        self.AngularStepLabel.setText(_translate("InputDialog", "Angular Step Size"))
        self.MaxWidthLabel.setText(_translate("InputDialog", "Max Material Width"))
        self.MaxHeightLabel.setText(_translate("InputDialog", "Max Material Height"))
        self.KerfLabel.setText(_translate("InputDialog", "Kerf Offset"))
        self.KerfLabel_2.setText(_translate("InputDialog", "Rasterization Resolution"))
        self.GeometryGroup.setTitle(_translate("InputDialog", "Geometry Set"))
        self.CloseButton.setText(_translate("InputDialog", "&Close"))
        self.RunButton.setText(_translate("InputDialog", "&Run"))
