# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputDialog(object):
    def setupUi(self, InputDialog):
        InputDialog.setObjectName("InputDialog")
        InputDialog.resize(701, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InputDialog.sizePolicy().hasHeightForWidth())
        InputDialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        InputDialog.setFont(font)
        self.BrowseButton = QtWidgets.QPushButton(InputDialog)
        self.BrowseButton.setGeometry(QtCore.QRect(10, 500, 121, 41))
        self.BrowseButton.setObjectName("BrowseButton")
        self.GeneticAlgorithmGroup = QtWidgets.QGroupBox(InputDialog)
        self.GeneticAlgorithmGroup.setGeometry(QtCore.QRect(380, 10, 311, 151))
        self.GeneticAlgorithmGroup.setObjectName("GeneticAlgorithmGroup")
        self.PopulationSpinner = QtWidgets.QSpinBox(self.GeneticAlgorithmGroup)
        self.PopulationSpinner.setGeometry(QtCore.QRect(160, 20, 61, 22))
        self.PopulationSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PopulationSpinner.setMinimum(1)
        self.PopulationSpinner.setMaximum(1000)
        self.PopulationSpinner.setSingleStep(25)
        self.PopulationSpinner.setProperty("value", 200)
        self.PopulationSpinner.setObjectName("PopulationSpinner")
        self.PopulationLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.PopulationLabel.setGeometry(QtCore.QRect(16, 20, 111, 20))
        self.PopulationLabel.setObjectName("PopulationLabel")
        self.IterationSpinner = QtWidgets.QSpinBox(self.GeneticAlgorithmGroup)
        self.IterationSpinner.setGeometry(QtCore.QRect(160, 50, 61, 22))
        self.IterationSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IterationSpinner.setMinimum(1)
        self.IterationSpinner.setMaximum(100000)
        self.IterationSpinner.setSingleStep(25)
        self.IterationSpinner.setProperty("value", 300)
        self.IterationSpinner.setObjectName("IterationSpinner")
        self.IterationLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.IterationLabel.setGeometry(QtCore.QRect(16, 50, 111, 20))
        self.IterationLabel.setObjectName("IterationLabel")
        self.MutationLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.MutationLabel.setGeometry(QtCore.QRect(16, 80, 111, 20))
        self.MutationLabel.setObjectName("MutationLabel")
        self.SpawnLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.SpawnLabel.setGeometry(QtCore.QRect(16, 110, 111, 20))
        self.SpawnLabel.setObjectName("SpawnLabel")
        self.MutationSpinner = QtWidgets.QDoubleSpinBox(self.GeneticAlgorithmGroup)
        self.MutationSpinner.setGeometry(QtCore.QRect(160, 80, 61, 22))
        self.MutationSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MutationSpinner.setDecimals(3)
        self.MutationSpinner.setMaximum(0.999)
        self.MutationSpinner.setSingleStep(0.01)
        self.MutationSpinner.setProperty("value", 0.03)
        self.MutationSpinner.setObjectName("MutationSpinner")
        self.SpawnSpinner = QtWidgets.QDoubleSpinBox(self.GeneticAlgorithmGroup)
        self.SpawnSpinner.setGeometry(QtCore.QRect(160, 110, 61, 22))
        self.SpawnSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SpawnSpinner.setDecimals(3)
        self.SpawnSpinner.setMaximum(0.999)
        self.SpawnSpinner.setSingleStep(0.01)
        self.SpawnSpinner.setProperty("value", 0.03)
        self.SpawnSpinner.setObjectName("SpawnSpinner")
        self.NestingGroup = QtWidgets.QGroupBox(InputDialog)
        self.NestingGroup.setGeometry(QtCore.QRect(380, 170, 311, 321))
        self.NestingGroup.setObjectName("NestingGroup")
        self.MagetLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MagetLabel.setGeometry(QtCore.QRect(10, 20, 111, 20))
        self.MagetLabel.setObjectName("MagetLabel")
        self.MagnetCombo = QtWidgets.QComboBox(self.NestingGroup)
        self.MagnetCombo.setGeometry(QtCore.QRect(160, 20, 141, 22))
        self.MagnetCombo.setObjectName("MagnetCombo")
        self.OpenLoopLabel = QtWidgets.QLabel(self.NestingGroup)
        self.OpenLoopLabel.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.OpenLoopLabel.setObjectName("OpenLoopLabel")
        self.OpenLoopCombo = QtWidgets.QComboBox(self.NestingGroup)
        self.OpenLoopCombo.setGeometry(QtCore.QRect(160, 50, 141, 22))
        self.OpenLoopCombo.setObjectName("OpenLoopCombo")
        self.InnerShapeLabel = QtWidgets.QLabel(self.NestingGroup)
        self.InnerShapeLabel.setGeometry(QtCore.QRect(10, 80, 111, 20))
        self.InnerShapeLabel.setObjectName("InnerShapeLabel")
        self.InnerShapeCombo = QtWidgets.QComboBox(self.NestingGroup)
        self.InnerShapeCombo.setGeometry(QtCore.QRect(160, 80, 141, 22))
        self.InnerShapeCombo.setObjectName("InnerShapeCombo")
        self.LinearStepLabel = QtWidgets.QLabel(self.NestingGroup)
        self.LinearStepLabel.setGeometry(QtCore.QRect(10, 140, 121, 20))
        self.LinearStepLabel.setObjectName("LinearStepLabel")
        self.AngularStepLabel = QtWidgets.QLabel(self.NestingGroup)
        self.AngularStepLabel.setGeometry(QtCore.QRect(10, 170, 121, 20))
        self.AngularStepLabel.setObjectName("AngularStepLabel")
        self.MaxWidthLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MaxWidthLabel.setGeometry(QtCore.QRect(10, 200, 121, 20))
        self.MaxWidthLabel.setObjectName("MaxWidthLabel")
        self.MaxHeightLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MaxHeightLabel.setGeometry(QtCore.QRect(10, 230, 121, 20))
        self.MaxHeightLabel.setObjectName("MaxHeightLabel")
        self.KerfLabel = QtWidgets.QLabel(self.NestingGroup)
        self.KerfLabel.setGeometry(QtCore.QRect(10, 260, 111, 20))
        self.KerfLabel.setObjectName("KerfLabel")
        self.ResolutionSpinner = QtWidgets.QSpinBox(self.NestingGroup)
        self.ResolutionSpinner.setGeometry(QtCore.QRect(160, 290, 71, 22))
        self.ResolutionSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ResolutionSpinner.setProperty("value", 1)
        self.ResolutionSpinner.setObjectName("ResolutionSpinner")
        self.ResolutionLabel = QtWidgets.QLabel(self.NestingGroup)
        self.ResolutionLabel.setGeometry(QtCore.QRect(10, 290, 141, 20))
        self.ResolutionLabel.setObjectName("ResolutionLabel")
        self.AngularStepSpinner = QtWidgets.QDoubleSpinBox(self.NestingGroup)
        self.AngularStepSpinner.setGeometry(QtCore.QRect(160, 170, 71, 22))
        self.AngularStepSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AngularStepSpinner.setDecimals(1)
        self.AngularStepSpinner.setMinimum(0.0)
        self.AngularStepSpinner.setMaximum(180.0)
        self.AngularStepSpinner.setSingleStep(5.0)
        self.AngularStepSpinner.setProperty("value", 45.0)
        self.AngularStepSpinner.setObjectName("AngularStepSpinner")
        self.LinearStepSpinner = QtWidgets.QDoubleSpinBox(self.NestingGroup)
        self.LinearStepSpinner.setGeometry(QtCore.QRect(160, 140, 71, 22))
        self.LinearStepSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LinearStepSpinner.setDecimals(1)
        self.LinearStepSpinner.setMinimum(0.0)
        self.LinearStepSpinner.setMaximum(50.0)
        self.LinearStepSpinner.setSingleStep(0.1)
        self.LinearStepSpinner.setProperty("value", 5.0)
        self.LinearStepSpinner.setObjectName("LinearStepSpinner")
        self.MaxWidthSpinner = QtWidgets.QDoubleSpinBox(self.NestingGroup)
        self.MaxWidthSpinner.setGeometry(QtCore.QRect(160, 200, 71, 22))
        self.MaxWidthSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MaxWidthSpinner.setDecimals(1)
        self.MaxWidthSpinner.setMinimum(0.0)
        self.MaxWidthSpinner.setMaximum(5000.0)
        self.MaxWidthSpinner.setSingleStep(50.0)
        self.MaxWidthSpinner.setProperty("value", 0.0)
        self.MaxWidthSpinner.setObjectName("MaxWidthSpinner")
        self.MaxHeightSpinner = QtWidgets.QDoubleSpinBox(self.NestingGroup)
        self.MaxHeightSpinner.setGeometry(QtCore.QRect(160, 230, 71, 22))
        self.MaxHeightSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MaxHeightSpinner.setDecimals(1)
        self.MaxHeightSpinner.setMinimum(0.0)
        self.MaxHeightSpinner.setMaximum(5000.0)
        self.MaxHeightSpinner.setSingleStep(50.0)
        self.MaxHeightSpinner.setProperty("value", 0.0)
        self.MaxHeightSpinner.setObjectName("MaxHeightSpinner")
        self.KerfSpinner = QtWidgets.QDoubleSpinBox(self.NestingGroup)
        self.KerfSpinner.setGeometry(QtCore.QRect(160, 260, 71, 22))
        self.KerfSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.KerfSpinner.setDecimals(1)
        self.KerfSpinner.setMinimum(0.0)
        self.KerfSpinner.setMaximum(10.0)
        self.KerfSpinner.setSingleStep(0.1)
        self.KerfSpinner.setProperty("value", 0.0)
        self.KerfSpinner.setObjectName("KerfSpinner")
        self.LinearStepUnitLabel = QtWidgets.QLabel(self.NestingGroup)
        self.LinearStepUnitLabel.setGeometry(QtCore.QRect(230, 140, 31, 20))
        self.LinearStepUnitLabel.setObjectName("LinearStepUnitLabel")
        self.AngularStepUnitLabel = QtWidgets.QLabel(self.NestingGroup)
        self.AngularStepUnitLabel.setGeometry(QtCore.QRect(230, 170, 71, 20))
        self.AngularStepUnitLabel.setObjectName("AngularStepUnitLabel")
        self.MaxWidthUnitLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MaxWidthUnitLabel.setGeometry(QtCore.QRect(230, 200, 31, 20))
        self.MaxWidthUnitLabel.setObjectName("MaxWidthUnitLabel")
        self.MaxHeightUnitLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MaxHeightUnitLabel.setGeometry(QtCore.QRect(230, 230, 31, 20))
        self.MaxHeightUnitLabel.setObjectName("MaxHeightUnitLabel")
        self.KerfUnitLabel = QtWidgets.QLabel(self.NestingGroup)
        self.KerfUnitLabel.setGeometry(QtCore.QRect(230, 260, 31, 20))
        self.KerfUnitLabel.setObjectName("KerfUnitLabel")
        self.ResolutionUnitLabel = QtWidgets.QLabel(self.NestingGroup)
        self.ResolutionUnitLabel.setGeometry(QtCore.QRect(230, 290, 71, 20))
        self.ResolutionUnitLabel.setObjectName("ResolutionUnitLabel")
        self.AllowFlipLabel = QtWidgets.QLabel(self.NestingGroup)
        self.AllowFlipLabel.setGeometry(QtCore.QRect(10, 110, 111, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AllowFlipLabel.sizePolicy().hasHeightForWidth())
        self.AllowFlipLabel.setSizePolicy(sizePolicy)
        self.AllowFlipLabel.setObjectName("AllowFlipLabel")
        self.AllowFlipCombo = QtWidgets.QComboBox(self.NestingGroup)
        self.AllowFlipCombo.setGeometry(QtCore.QRect(160, 110, 141, 22))
        self.AllowFlipCombo.setObjectName("AllowFlipCombo")
        self.GeometryGroup = QtWidgets.QGroupBox(InputDialog)
        self.GeometryGroup.setGeometry(QtCore.QRect(10, 10, 361, 481))
        self.GeometryGroup.setObjectName("GeometryGroup")
        self.gridLayoutWidget = QtWidgets.QWidget(self.GeometryGroup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 351, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.GeometryListLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.GeometryListLayout.setContentsMargins(0, 0, 0, 0)
        self.GeometryListLayout.setObjectName("GeometryListLayout")
        self.CloseButton = QtWidgets.QPushButton(InputDialog)
        self.CloseButton.setGeometry(QtCore.QRect(570, 500, 121, 41))
        self.CloseButton.setObjectName("CloseButton")
        self.RunButton = QtWidgets.QPushButton(InputDialog)
        self.RunButton.setGeometry(QtCore.QRect(440, 500, 121, 41))
        self.RunButton.setObjectName("RunButton")

        self.retranslateUi(InputDialog)
        QtCore.QMetaObject.connectSlotsByName(InputDialog)

    def retranslateUi(self, InputDialog):
        _translate = QtCore.QCoreApplication.translate
        InputDialog.setWindowTitle(_translate("InputDialog", "Nesting"))
        self.BrowseButton.setText(_translate("InputDialog", "&Browse"))
        self.GeneticAlgorithmGroup.setTitle(_translate("InputDialog", "Genetic Algorithm"))
        self.PopulationLabel.setText(_translate("InputDialog", "Population"))
        self.IterationLabel.setText(_translate("InputDialog", "Iterations"))
        self.MutationLabel.setText(_translate("InputDialog", "Mutation Rate"))
        self.SpawnLabel.setText(_translate("InputDialog", "Spawn Rate"))
        self.NestingGroup.setTitle(_translate("InputDialog", "Nesting Process"))
        self.MagetLabel.setText(_translate("InputDialog", "Magnet"))
        self.OpenLoopLabel.setText(_translate("InputDialog", "Open Loop Action"))
        self.InnerShapeLabel.setText(_translate("InputDialog", "Allow Inner Shapes"))
        self.LinearStepLabel.setText(_translate("InputDialog", "Linear Step Size"))
        self.AngularStepLabel.setText(_translate("InputDialog", "Angular Step Size"))
        self.MaxWidthLabel.setText(_translate("InputDialog", "Max Material Width"))
        self.MaxHeightLabel.setText(_translate("InputDialog", "Max Material Height"))
        self.KerfLabel.setText(_translate("InputDialog", "Kerf Offset"))
        self.ResolutionLabel.setText(_translate("InputDialog", "Rasterization Resolution"))
        self.LinearStepUnitLabel.setText(_translate("InputDialog", "mm"))
        self.AngularStepUnitLabel.setText(_translate("InputDialog", "degrees"))
        self.MaxWidthUnitLabel.setText(_translate("InputDialog", "mm"))
        self.MaxHeightUnitLabel.setText(_translate("InputDialog", "mm"))
        self.KerfUnitLabel.setText(_translate("InputDialog", "mm"))
        self.ResolutionUnitLabel.setText(_translate("InputDialog", "mm/pixel"))
        self.AllowFlipLabel.setText(_translate("InputDialog", "Allow Flip"))
        self.GeometryGroup.setTitle(_translate("InputDialog", "Geometry Set"))
        self.CloseButton.setText(_translate("InputDialog", "&Close"))
        self.RunButton.setText(_translate("InputDialog", "&Run"))
