# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputWindow(object):
    def setupUi(self, InputWindow):
        InputWindow.setObjectName("InputWindow")
        InputWindow.resize(685, 491)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InputWindow.sizePolicy().hasHeightForWidth())
        InputWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        InputWindow.setFont(font)
        self.BrowseButton = QtWidgets.QPushButton(InputWindow)
        self.BrowseButton.setGeometry(QtCore.QRect(10, 440, 121, 41))
        self.BrowseButton.setObjectName("BrowseButton")
        self.GeneticAlgorithmGroup = QtWidgets.QGroupBox(InputWindow)
        self.GeneticAlgorithmGroup.setGeometry(QtCore.QRect(380, 10, 291, 151))
        self.GeneticAlgorithmGroup.setObjectName("GeneticAlgorithmGroup")
        self.PopulationSpinner = QtWidgets.QSpinBox(self.GeneticAlgorithmGroup)
        self.PopulationSpinner.setGeometry(QtCore.QRect(140, 20, 141, 22))
        self.PopulationSpinner.setObjectName("PopulationSpinner")
        self.PopulationLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.PopulationLabel.setGeometry(QtCore.QRect(16, 20, 111, 20))
        self.PopulationLabel.setObjectName("PopulationLabel")
        self.IterationSpinner = QtWidgets.QSpinBox(self.GeneticAlgorithmGroup)
        self.IterationSpinner.setGeometry(QtCore.QRect(140, 50, 141, 22))
        self.IterationSpinner.setObjectName("IterationSpinner")
        self.IterationLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.IterationLabel.setGeometry(QtCore.QRect(16, 50, 111, 20))
        self.IterationLabel.setObjectName("IterationLabel")
        self.MutationSpinner = QtWidgets.QSpinBox(self.GeneticAlgorithmGroup)
        self.MutationSpinner.setGeometry(QtCore.QRect(140, 80, 141, 22))
        self.MutationSpinner.setObjectName("MutationSpinner")
        self.MutationLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.MutationLabel.setGeometry(QtCore.QRect(16, 80, 111, 20))
        self.MutationLabel.setObjectName("MutationLabel")
        self.SpawnSpinner = QtWidgets.QSpinBox(self.GeneticAlgorithmGroup)
        self.SpawnSpinner.setGeometry(QtCore.QRect(140, 110, 141, 22))
        self.SpawnSpinner.setObjectName("SpawnSpinner")
        self.SpawnLabel = QtWidgets.QLabel(self.GeneticAlgorithmGroup)
        self.SpawnLabel.setGeometry(QtCore.QRect(16, 110, 111, 20))
        self.SpawnLabel.setObjectName("SpawnLabel")
        self.NestingGroup = QtWidgets.QGroupBox(InputWindow)
        self.NestingGroup.setGeometry(QtCore.QRect(380, 170, 291, 261))
        self.NestingGroup.setObjectName("NestingGroup")
        self.MagetLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MagetLabel.setGeometry(QtCore.QRect(10, 20, 111, 20))
        self.MagetLabel.setObjectName("MagetLabel")
        self.MagnetCombo = QtWidgets.QComboBox(self.NestingGroup)
        self.MagnetCombo.setGeometry(QtCore.QRect(140, 20, 141, 22))
        self.MagnetCombo.setObjectName("MagnetCombo")
        self.OpenLoopAngle = QtWidgets.QLabel(self.NestingGroup)
        self.OpenLoopAngle.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.OpenLoopAngle.setObjectName("OpenLoopAngle")
        self.OpenLoopCombo = QtWidgets.QComboBox(self.NestingGroup)
        self.OpenLoopCombo.setGeometry(QtCore.QRect(140, 50, 141, 22))
        self.OpenLoopCombo.setObjectName("OpenLoopCombo")
        self.InnerShapeLabel = QtWidgets.QLabel(self.NestingGroup)
        self.InnerShapeLabel.setGeometry(QtCore.QRect(10, 80, 111, 20))
        self.InnerShapeLabel.setObjectName("InnerShapeLabel")
        self.InnerShapeCombo = QtWidgets.QComboBox(self.NestingGroup)
        self.InnerShapeCombo.setGeometry(QtCore.QRect(140, 80, 141, 22))
        self.InnerShapeCombo.setObjectName("InnerShapeCombo")
        self.LinearStepLabel = QtWidgets.QLabel(self.NestingGroup)
        self.LinearStepLabel.setGeometry(QtCore.QRect(10, 110, 121, 20))
        self.LinearStepLabel.setObjectName("LinearStepLabel")
        self.AngularStepLabel = QtWidgets.QLabel(self.NestingGroup)
        self.AngularStepLabel.setGeometry(QtCore.QRect(10, 140, 121, 20))
        self.AngularStepLabel.setObjectName("AngularStepLabel")
        self.MaxWidthLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MaxWidthLabel.setGeometry(QtCore.QRect(10, 170, 121, 20))
        self.MaxWidthLabel.setObjectName("MaxWidthLabel")
        self.MaxHeightLabel = QtWidgets.QLabel(self.NestingGroup)
        self.MaxHeightLabel.setGeometry(QtCore.QRect(10, 200, 121, 20))
        self.MaxHeightLabel.setObjectName("MaxHeightLabel")
        self.KerfLabel = QtWidgets.QLabel(self.NestingGroup)
        self.KerfLabel.setGeometry(QtCore.QRect(10, 230, 111, 20))
        self.KerfLabel.setObjectName("KerfLabel")
        self.MaxHeightSpinner = QtWidgets.QSpinBox(self.NestingGroup)
        self.MaxHeightSpinner.setGeometry(QtCore.QRect(140, 200, 141, 22))
        self.MaxHeightSpinner.setObjectName("MaxHeightSpinner")
        self.KerfSpinner = QtWidgets.QSpinBox(self.NestingGroup)
        self.KerfSpinner.setGeometry(QtCore.QRect(140, 230, 141, 22))
        self.KerfSpinner.setObjectName("KerfSpinner")
        self.AngularStepSpinner = QtWidgets.QSpinBox(self.NestingGroup)
        self.AngularStepSpinner.setGeometry(QtCore.QRect(140, 140, 141, 22))
        self.AngularStepSpinner.setObjectName("AngularStepSpinner")
        self.MaxWidthSpinner = QtWidgets.QSpinBox(self.NestingGroup)
        self.MaxWidthSpinner.setGeometry(QtCore.QRect(140, 170, 141, 22))
        self.MaxWidthSpinner.setObjectName("MaxWidthSpinner")
        self.LinearStepCombo = QtWidgets.QSpinBox(self.NestingGroup)
        self.LinearStepCombo.setGeometry(QtCore.QRect(140, 110, 141, 22))
        self.LinearStepCombo.setObjectName("LinearStepCombo")
        self.GeometryGroup = QtWidgets.QGroupBox(InputWindow)
        self.GeometryGroup.setGeometry(QtCore.QRect(10, 10, 361, 421))
        self.GeometryGroup.setObjectName("GeometryGroup")
        self.GeometryListArea = QtWidgets.QScrollArea(self.GeometryGroup)
        self.GeometryListArea.setGeometry(QtCore.QRect(9, 19, 341, 391))
        self.GeometryListArea.setWidgetResizable(True)
        self.GeometryListArea.setObjectName("GeometryListArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 339, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.GeometryListArea.setWidget(self.scrollAreaWidgetContents)
        self.CloseButton = QtWidgets.QPushButton(InputWindow)
        self.CloseButton.setGeometry(QtCore.QRect(550, 440, 121, 41))
        self.CloseButton.setObjectName("CloseButton")
        self.RunButton = QtWidgets.QPushButton(InputWindow)
        self.RunButton.setGeometry(QtCore.QRect(420, 440, 121, 41))
        self.RunButton.setObjectName("RunButton")

        self.retranslateUi(InputWindow)
        QtCore.QMetaObject.connectSlotsByName(InputWindow)

    def retranslateUi(self, InputWindow):
        _translate = QtCore.QCoreApplication.translate
        InputWindow.setWindowTitle(_translate("InputWindow", "Nesting"))
        self.BrowseButton.setText(_translate("InputWindow", "&Browse"))
        self.GeneticAlgorithmGroup.setTitle(_translate("InputWindow", "Genetic Algorithm"))
        self.PopulationLabel.setText(_translate("InputWindow", "Population"))
        self.IterationLabel.setText(_translate("InputWindow", "Iterations"))
        self.MutationLabel.setText(_translate("InputWindow", "Mutation Rate"))
        self.SpawnLabel.setText(_translate("InputWindow", "Spawn Rate"))
        self.NestingGroup.setTitle(_translate("InputWindow", "Nesting Process"))
        self.MagetLabel.setText(_translate("InputWindow", "Magnet"))
        self.OpenLoopAngle.setText(_translate("InputWindow", "Open Loop Action"))
        self.InnerShapeLabel.setText(_translate("InputWindow", "Allow Inner Shapes"))
        self.LinearStepLabel.setText(_translate("InputWindow", "Linear Step Size"))
        self.AngularStepLabel.setText(_translate("InputWindow", "Angular Step Size"))
        self.MaxWidthLabel.setText(_translate("InputWindow", "Max Material Width"))
        self.MaxHeightLabel.setText(_translate("InputWindow", "Max Material Height"))
        self.KerfLabel.setText(_translate("InputWindow", "Kerf Offset"))
        self.GeometryGroup.setTitle(_translate("InputWindow", "Geometry Set"))
        self.CloseButton.setText(_translate("InputWindow", "&Close"))
        self.RunButton.setText(_translate("InputWindow", "&Run"))
